[package]
name = "md-tui"
version = "0.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "0.24.1"
crossterm = "0.27.0"
ratatui = "0.26.3"
tui-textarea = "0.4.0"
